---
version: 2.1
# commit 120
jobs:
  sayhello: # defines a parameterized job
    description: Demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    machine: true
    steps:
      - run: echo "Hello << parameters.saywhat >>"

  buildtest:
    parameters:
      perlv:
        description: "The Perl version we want to do the build and test with"
        default: "5.32"
        type: string
    docker:
      # - image: perldocker/perl-tester:<< pipeline.parameters.perlv >>
      - image: perldocker/perl-tester:<< parameters.perlv >>


workflows:
  build:
    jobs:
      - sayhello: # invokes the parameterized job
          saywhat: Everyone
      - buildtest:
          perlv: "5.26"
