version: 2.1

parameters:
  perl-version:
    default: "5.32"
    description: The Perl version we want to do the build and test with
    type: string

jobs:
  parameters:
    perl-version:
      default: "5.32"
      description: The Perl version we want to do the build and test with
      type: string

  build:
    docker:
      - image: perldocker/perl-tester:<< parameters.perl-version >>

# working_directory: Hello
# when given at job level goes to /tmp/Hello
# when given at the step level goes to /root/project/Hello

    steps:
      - checkout

  test:
    docker:
      - image: perldocker/perl-tester:<< parameters.perl-version >>
    steps:
      - run:
          command: perl -V; pwd;
          # working_directory: Hello
      - run:
          # description: Install Hello dependencies
          command: pwd; dzil listdeps | xargs cpanm;
          working_directory: Hello
      - run:
          description: Test Hello
          command: prove -l t/*.t
          working_directory: Hello

workflows:
  Hello_Perl_App: # this is the name of our workflow
    jobs:
      - build
      - test:
        requires: build
        matrix:
          parameters:
            perl-version:
              - '5.22'
              - '5.32'
