version: 2.1

jobs:


  buildtest:

    parameters:
      perlv:
        # default: "5.32"
        description: The Perl version we want to do the build and test with
        type: string

    docker:
      # - image: perldocker/perl-tester:<< pipeline.parameters.perlv >>
      - image: perldocker/perl-tester:<< perlv >>

    # working_directory: Hello
    # when given at job level goes to /tmp/Hello
    # when given at the step level goes to /root/project/Hello

    steps:
      - checkout
      - run:
          command: perl -V; pwd;
          # working_directory: Hello
      - run:
          # description: Install Hello dependencies
          command: pwd; dzil listdeps | xargs cpanm;
          working_directory: Hello
      - run:
          description: Test Hello
          command: prove -l t/*.t
          working_directory: Hello

workflows:
  Hello_Perl_App: # this is the name of our workflow
    jobs:
      - buildtest:
        matrix:
          parameters:
            perlv: ["5.22", "5.28"]


# workflows:
#   workflow:
#     jobs:
#       - build:
#           matrix:
#             parameters:
#               version: ["0.1", "0.2", "0.3"]
#               platform: ["macos", "windows", "linux"]