version: 2.1

parameters:
  perlv:
    default: "5.32"
    description: The Perl version we want to do the build and test with
    type: string

jobs:

  buildtest:

    docker:
      # - image: perldocker/perl-tester:<< parameters.perlv >>
      - image: perldocker/perl-tester:<< parameters.perlv >>

    # working_directory: Hello
    # when given at job level goes to /tmp/Hello
    # when given at the step level goes to /root/project/Hello

    steps:
      - checkout
      - run:
          command: perl -V; pwd;
          # working_directory: Hello
      - run:
          # description: Install Hello dependencies
          command: pwd; dzil listdeps | xargs cpanm;
          working_directory: Hello
      - run:
          description: Test Hello
          command: prove -l t/*.t
          working_directory: Hello

workflows:
  Hello_Perl_App: # this is the name of our workflow
    jobs:
      - buildtest
        # parameters:
        #   perlv: '5.22'
        # matrix:
          # parameters:
          #   perlv: '5.22'
              # - '5.32'
