version: 2.1

parameters:
  perl-version:
    default: "5.32"
    description: The Perl version we want to do the build and test with
    type: string

jobs:
  build:
    docker:
      - image: perldocker/perl-tester:<< parameters.perl-version >>
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test:
    docker:
      - image: perldocker/perl-tester:<< parameters.perl-version >>
    steps:
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  # Run-With-Node:
  #   docker:
  #     - image: circleci/node:10-browsers
  #   steps:
  #     - run:
  #         name: Running In A Container With Node
  #         command: |
  #           node -v
  # Now-Complete:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Approval Complete
  #         command: |
  #           echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
  jobs:
    - build
      # parameters:
      #   perl-version: 5.26
    - test:
      requires:
        - build
      # parameters:
      #   perl-version: 5.26
    #  - Run-With-Node:
    #      requires:
    #        - Hello-World
    #  - Hold-For-Approval:
    #      type: approval
    #      requires:
    #        - Run-With-Node
    #        - I-Have-Code
    #  - Now-Complete:
    #      requires:
    #        - Hold-For-Approval

