---
version: 2.1
# commit 118
jobs:
  sayhello: # defines a parameterized job
    description: A job that does very little other than demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    machine: true
    steps:
      - run: echo "Hello << parameters.saywhat >>"

  buildtest:
    parameters:
      perlv:
        # default: "5.32"
        description: The Perl version we want to do the build and test with
        type: string
    docker:
      # - image: perldocker/perl-tester:<< pipeline.parameters.perlv >>
      - image: perldocker/perl-tester:<< parameters.perlv >>


workflows:
  build:
    jobs:
      - sayhello: # invokes the parameterized job
          saywhat: Everyone
      - buildtest:
          perlv: "5.26"