---
version: 2.1
# commit 127
jobs:
  sayhello: # defines a parameterized job
    description: Demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    machine: true
    steps:
      - run: echo "Hello << parameters.saywhat >>"

  buildtest:
    parameters:
      perlv:
        description: "The Perl version we want to do the build and test with"
        # default: "5.32"
        type: string
    docker:
      # - image: perldocker/perl-tester:<< pipeline.parameters.perlv >>
      - image: perldocker/perl-tester:<< parameters.perlv >>
    steps:
      - checkout
      - run:
          command: perl -V; pwd;
          # working_directory: Hello
      - run:
          # description: Install Hello dependencies
          command: pwd; dzil listdeps | xargs cpanm;
          working_directory: Hello
      - run:
          description: Test Hello
          command: prove -l t/*.t
          working_directory: Hello

workflows:
  build:
    jobs:
      - sayhello: # invokes the parameterized job
          saywhat: Everyone
      - buildtest:
          matrix:
            parameters:
              perlv:
                - '5.22'
                - '5.28'
    #  - build:
    #       matrix:
    #         parameters:
    #           version: ["0.1", "0.2", "0.3"]
    #           platform: ["macos", "windows", "linux"]
      # - buildtest:
      #     perlv: "5.26"
